name: baby_lc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  carousel_slider: ^4.2.1
  top_snackbar_flutter: ^3.1.0
  flutter_otp_text_field: ^1.1.1
  dropdown_search: ^5.0.6
  http: ^1.1.0
  url_launcher: ^6.1.12
  get: 4.6.5
  flutter: 
    sdk: flutter
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  lottie: ^2.6.0
  image_picker: ^1.0.2
  provider: ^6.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/images/
    - asset/lottie/
  uses-material-design: true


  fonts:
     - family: Arial
       fonts:
         - asset: asset/fonts/Arial-Rounded-MT-Bold.ttf 
     - family: Myriad
       fonts:
         - asset: asset/fonts/MyriadPro-Regular.ttf
     